### ISSUE TITLE
Cant compile

### ISSUE THREAD

**Issue by PandemRus** [intucoin/INTUcoin#2]
Ubuntu 16.04 Server.
When I try to compile, i got error:

/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
[  5%] Building CXX object src/CMakeFiles/PaymentGate.dir/PaymentGate/PaymentServiceJsonRpcMessages.cpp.o
In file included from /usr/include/c++/5/unordered_map:35:0,
                 from ./include/rocksdb/options.h:18,
                 from ./util/testutil.h:20,
                 from util/testutil.cc:10:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
[  5%] Building C object src/CMakeFiles/Crypto.dir/crypto/blake256.c.o
In file included from /usr/include/c++/5/unordered_map:35:0,
                 from ./include/rocksdb/db.h:16,
                 from ./db/dbformat.h:14,
                 from ./tools/sst_dump_tool_imp.h:12,
                 from tools/sst_dump_tool.cc:8:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \

**Comment by ArqTras** [comment]
Change permission to files
https://github.com/intucoin/INTUcoin/tree/master/external/rocksdb/build_tools

**Comment by intucoin** [comment]
Fixed
